### PR TITLE
Increase tests and add scripts for auto fixing code

### PR DESCRIPTION
**Pull request by pwirth**
https://github.com/inblockio/DataAccounting/issues/150

### CODE REVIEW

**Comment by pwirth** [comment]
to much changes will lead to merge conflicts

**Comment by FantasticoFox** [comment]
You're doing it in smaller commits? Would be a pity to see disregards valuable work.

**Comment by pwirth** [comment]
yes, that is what i am trying to do right now in https://github.com/inblockio/DataAccounting/pull/213

**Comment by rht** [comment]
@pwirth  can the branch `codequality` be deleted?

**Comment by pwirth** [comment]
yes, of course. ill delete it :)

**Pull request closed without merging**
